{% set name = "awswrangler" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9a2384ec4dbfd83ac8cef859d127924f89b3b3f1b6242da89606a296af3d68ec

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7.1,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.7.1,<4.0
    - boto3 >=1.24.11,<2.0.0
    - botocore >=1.27.11,<2.0.0
    - pandas >=1.2.0,<2.0,!=1.5.0
    - pyarrow >=7.0.0,<10.1.0
    - numpy >=1.18.0,<2.0.0
    - typing-extensions >=4.4.0,<5.0

test:
  imports:
    - awswrangler
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://aws-sdk-pandas.readthedocs.io
  summary: Pandas on AWS
  description: |
    An open-source Python package that extends the power of Pandas library to AWS connecting DataFrames
    and AWS data related services. Easy integration with Athena, Redshift, Glue, Timestream, Neptune,
    OpenSearch, QuickSight, Chime, CloudWatchLogs, DynamoDB, EMR, SecretManager, PostgreSQL, MySQL, SQLServer
    and S3 (Parquet, CSV, JSON and EXCEL).

    Built on top of other open-source projects like Pandas, Apache Arrow and Boto3,
    it offers abstracted functions to execute usual ETL tasks like load/unload
    data from Data Lakes, Data Warehouses and Databases.
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE.txt
    - NOTICE.txt
    - THIRD_PARTY.txt
  dev_url: https://github.com/aws/aws-sdk-pandas
  doc_url: https://aws-sdk-pandas.readthedocs.io

extra:
  recipe-maintainers:
    - nicolas-geniteau
    - maximerihouey
    - ncolomer
    - igorborgest
    - jaidisido
    - kukushking
    - BastianZim
    - malachi-constant
    - cnfait
    - LeonLuttenberger
